name: 'Sparky AI'
description: 'Installs and configures base requirements for Drupal AI integration'
type: 'Site'

install:
  # AI base modules
  - ai
  - ai_provider_openai
  - ai_provider_anthropic
  - key
input:
  provider:
    data_type: string
    description: 'AI provider'
    prompt:
      method: choice
      arguments:
        question: 'Choose your AI provider'
        choices:
          1: Open AI
          2: Anthropic
    default:
      source: value
      value: 'openai'
  #openai_api_key:
  #  data_type: string
  #  description: The OpenAI API key, if you want to use OpenAI.
  #  prompt:
  #    method: ask
  #    arguments:
  #      question: 'If you want to use OpenAI, enter your OpenAI API key. Otherwise, you can leave this empty:'
  #  default:
  #    source: value
  #    value: ''
  #anthropic_api_key:
  #  data_type: string
  #  description: The Anthropic API key, if you want to use Anthropic.
  #  prompt:
  #    method: ask
  #   arguments:
  #      question: 'If you want to use Anthropic, enter your Anthropic API key. Otherwise, you can leave this empty:'
  #  default:
  #    source: value
  #    value: ''
#config:
#  actions:
#    ai_provider_openai.settings:
#      setupAiProvider:
#        key_value: ${openai_api_key}
#        key_name: openai_api_key
#        key_label: 'OpenAI API Key'
#        provider: openai
#      simpleConfigUpdate:
#        moderation: true
#    ai_provider_anthropic.settings:
#      setupAiProvider:
#        key_value: ${anthropic_api_key}
#        key_name: anthropic_api_key
#        key_label: 'Anthropic API Key'
#        provider: anthropic
#      simpleConfigUpdate:
#        openai_moderation: false