name: 'Sparky Alt Tags'
description: 'Installs and configures the AI image alt text module.'
type: 'Site'
recipes:
  - sparky_ai
install:
  - ai_image_alt_text
config:
  import:
    ai_image_alt_text: '*'
