name: 'EC AI Base'
description: 'Installs and configures base requirements for AI integration'
type: 'Site'

install:
  # AI base modules
  - ai
  - ai_provider_openai
  - key
input:
  openai_api_key:
    data_type: string
    description: The OpenAI API key, if you want to use OpenAI.
    prompt:
      method: ask
      arguments:
        question: 'If you want to use OpenAI, enter your OpenAI API key. Otherwise, you can leave this empty:'
    default:
      source: value
      value: ''
config:
  actions:
    ai_provider_openai.settings:
      setupAiProvider:
        key_value: ${openai_api_key}
        key_name: openai_api_key
        key_label: 'OpenAI API Key'
        provider: openai
      simpleConfigUpdate:
        moderation: true